// ACTION TYPES
const GET_ALL_USERS = "GET_ALL_USERS";

const GET_BLOGS_ALL_USERS = "GET_BLOGS_ALL_USERS";

const GET_SINGLE_USER = "GET_SINGLE_USER";

const USER_LOGGED_IN = "USER_LOGGED_IN";

const DISPLAY_NOTIFICATION = "DISPLAY_NOTIFICATION";

const HIDE_NOTIFICATION = "HIDE_NOTIFICATION";

const ADD_BLOG = "ADD_BLOG";

const LIKE_BLOG = "LIKE_BLOG";

const DELETE_BLOG = "DELETE_BLOG";

export default {
  GET_ALL_USERS,
  GET_BLOGS_ALL_USERS,
  GET_SINGLE_USER,
  USER_LOGGED_IN,
  DISPLAY_NOTIFICATION,
  HIDE_NOTIFICATION,
  ADD_BLOG,
  LIKE_BLOG,
  DELETE_BLOG,
};
